version: '3.7'

services:
  web:
    build: ./app
    command: "uvicorn app.main:app --host 0.0.0.0 --port 80"
    volumes:
      - ./app/:/code/app/
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=yandex_user
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=yandex

volumes:
  postgres_data: